name: .NET Windows MacOS Linux Release

on:
  push:
    #branches:
    #  - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: windows-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .NET Core # Required to execute ReportGenerator
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
          dotnet-quality: 'ga'
        
      #- name: Install Chocolatey
      #  run: |
      #    Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      #  shell: powershell

      #- name: Install reportgenerator
      #  run: choco install reportgenerator.portable -y
      #  shell: powershell
        
      #- name: Install Doxygen
      #  run: choco install doxygen.install -y

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y
        shell: bash

      - name: Generate Documentation
        run: doxygen Doxyfile

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./CalculatorLibrary.Tests

      - name: Install coverlet.msbuild
        run: dotnet add package coverlet.msbuild --version 3.1.0
        working-directory: ./CalculatorLibrary.Tests

      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./CalculatorLibrary.Tests

      - name: Test with Coverage
        run: dotnet test --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --results-directory:./TestResults --logger:trx
        working-directory: ./CalculatorLibrary.Tests

      #- name: Generate Coverage Report
      #  run: reportgenerator "-reports:**/coverage.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Html

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.20
        with:
          reports: CalculatorLibrary.Tests/**/coverage.cobertura.xml
          targetdir: coveragereport
          reporttypes: Html;Html_Light;Html_Dark;Html_BlueRed;HtmlSummary;XML;XMLSummary;JsonSummary;Latex;TextSummary;TextDeltaSummary;MarkdownSummary;MarkdownSummaryGithub;MarkdownDeltaSummary;PngChart;Badges
          historydir: report_history
          filefilters: +cs;+java;+h;+cpp;+c
          title: 'PROJECT CODE COVERAGE'
        
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: CalculatorLibrary.Tests/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
          
      - name: Upload Code Coverage Results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-results
          path: code-coverage-results.md

    #  - name: Add Coverage PR Comment
    #    uses: marocchino/sticky-pull-request-comment@v2
    #    if: github.event_name == 'pull_request'
    #    with:
    #      recreate: true
    #      path: code-coverage-results.md
        
    #  - name: Check Test Coverage
    #    run: |
    #        $ErrorActionPreference = 'Stop'
    #        $coverageThreshold = 100.00
    #        $coverageReportPath = Get-ChildItem -Recurse -Filter 'coverage.cobertura.xml' | Select-Object -ExpandProperty FullName
    #        $lines = Get-Content $coverageReportPath
    #        $xmlContent = $lines -join "`n"
    #        $coverageXmlList = $xmlContent -split "<\?xml"
    #        $totalLines = 0
    #        $coveredLines = 0
    #        foreach ($coverageXmlString in $coverageXmlList) {
    #            if ($coverageXmlString.Trim() -ne '') {
    #                $coverageXmlString = "<?xml" + $coverageXmlString
    #                [xml]$coverageXml = $coverageXmlString
    #                $lineRate = $coverageXml.SelectSingleNode("//coverage").GetAttribute("line-rate")
    #                $coverage = [float]$lineRate * 100.00
    #                if ($coverage -lt $coverageThreshold) {
    #                    Write-Host "Current test coverage is below the threshold of $coverageThreshold%."
    #                    Write-Host "Current test coverage: $coverage%."
    #                    exit 1
    #                }
    #            }
    #        }
    #    shell: powershell

      - name : Check Test Coverage
        run: |
            #!/bin/bash
            sudo apt-get install -y libxml2-utils
            error_action_preference='Stop'
            coverage_threshold=100.00
            coverage_report_path=$(find . -name 'coverage.cobertura.xml' -type f -print -quit)
            lines=$(cat "$coverage_report_path")
            xml_content=$(echo "$lines" | tr -cd '[:print:]\n')
            coverage_xml_list=$(echo "$xml_content" | sed -e 's/<\?xml[^?]*\?>//' -e 's/<\?xml/\'$'\n<?xml/g' -e 's/<\//\'$'\n<\/\//g')
            total_lines=0
            covered_lines=0
            for coverage_xml_string in $coverage_xml_list; do
                if [[ -n "$coverage_xml_string" ]]; then
                    coverage_xml_string="<?xml$coverage_xml_string"
                    line_rate=$(echo "$coverage_xml_string" | xmllint --xpath '//coverage' - | awk -F '"' '/line-rate/{print $2}')
                    coverage=$(awk "BEGIN {print $line_rate * 100.00}")
                    if (( $(awk "BEGIN {print $coverage < $coverage_threshold} ") )); then
                        echo "Current test coverage is below the threshold of $coverage_threshold%."
                        echo "Current test coverage: $coverage%."
                        exit 1
                    fi
                fi
            done
        shell: bash

#      - name: Publish
#        run: dotnet publish --configuration Release --output publish
      - name: Build/Publish for Windows
        run: dotnet publish -c Release -r win-x64 --self-contained true -o publish/windows

      - name: Get Commit Summary
        id: commit_summary
        run: echo "::set-output name=summary::$(git log --format=%B -n 1 ${{ github.sha }})"

      - name: Create Release
        id: create_common_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NET_CORE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            ${{ steps.commit_summary.outputs.summary }}
            
            Dr. Ugur CORUH
          draft: false
          prerelease: false

      - name: Compress Windows binaries
        run: tar -czvf windows-binaries.tar.gz -C publish/windows .
        
      - name: Compress Windows Test Coverage Report
        run: tar -czvf test-coverage-html.tar.gz -C coveragereport .
        
      - name: Compress Doxygen Output (Html/Xml/Latex)
        run: tar -czvf doxygen-output-html-xml-latex.tar.gz -C Docs .
                
      - name: Upload Windows Binaries to release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_common_release.outputs.upload_url }}
          asset_path: ./windows-binaries.tar.gz
          asset_name: windows-binaries.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.NET_CORE_TOKEN }}

      - name: Upload Test Converage HTML Report to release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_common_release.outputs.upload_url }}
          asset_path: ./test-coverage-html.tar.gz
          asset_name: test-coverage-html.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.NET_CORE_TOKEN }}
          
          
      - name: Upload Doxygen Output to release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_common_release.outputs.upload_url }}
          asset_path: ./doxygen-output-html-xml-latex.tar.gz
          asset_name: doxygen-output-html-xml-latex.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.NET_CORE_TOKEN }}

      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.NET_CORE_TOKEN }}
          publish_dir: ./Docs/html
