name: .NET Windows MacOS Linux Release

on:
  push:
    tags:
      - 'v*'
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        
      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        shell: powershell

      - name: Install reportgenerator
        run: choco install reportgenerator.portable -y
        shell: powershell

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./CalculatorLibrary.Tests

      - name: Install coverlet.msbuild
        run: dotnet add package coverlet.msbuild --version 3.1.0
        working-directory: ./CalculatorLibrary.Tests

      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./CalculatorLibrary.Tests

      - name: Test with Coverage
        run: dotnet test --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --results-directory:./TestResults --logger:trx
        working-directory: ./CalculatorLibrary.Tests

      - name: Generate Coverage Report
        run: reportgenerator "-reports:**/coverage.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Html
        
      - name: Check Test Coverage
        run: |
          $ErrorActionPreference = 'Stop'
          $coverageThreshold = 100
          $coverageReportPath = Get-ChildItem -Recurse -Filter 'coverage.cobertura.xml' | Select-Object -ExpandProperty FullName
          $coverageReport = Get-Content $coverageReportPath | Select-String -Pattern '(?<=<LineCoverage>).*(?=<\/LineCoverage>)' | ForEach-Object { $_.Matches.Value }
     
          if ($coverageReport -lt $coverageThreshold) {
            Write-Host "Test coverage is below the threshold of $coverageThreshold%."
            exit 1
          } else {
            Write-Host "Test coverage is $coverageReport%."
          }
        shell: pwsh

#      - name: Publish
#        run: dotnet publish --configuration Release --output publish
      - name: Build/Publish for Windows
        run: dotnet publish -c Release -r win-x64 --self-contained true -o publish/windows

      - name: Get Commit Summary
        id: commit_summary
        run: echo "::set-output name=summary::$(git log --format=%B -n 1 ${{ github.sha }})"

      - name: Create Release
        id: create_common_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NET_CORE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            ${{ steps.commit_summary.outputs.summary }}
            
            Dr. Ugur CORUH
          draft: false
          prerelease: false

      - name: Compress Windows binaries
        run: tar -czvf windows-binaries.tar.gz -C publish/windows .
        
      - name: Compress Windows Test Coverage Report
        run: tar -czvf test-coverage-html.tar.gz -C coveragereport .
                
      - name: Upload Windows Binaries to release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_common_release.outputs.upload_url }}
          asset_path: ./windows-binaries.tar.gz
          asset_name: windows-binaries.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.NET_CORE_TOKEN }}

      - name: Upload Test Converage HTML Report to release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_common_release.outputs.upload_url }}
          asset_path: ./test-coverage-html.tar.gz
          asset_name: test-coverage-html.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.NET_CORE_TOKEN }}
